spring:
  application:
    name: web-crawler-and-notifier
  
  # Database Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  
  datasource:
    url: jdbc:h2:file:./data/crawlerdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        logging:
          parameters: true
    show-sql: false
  
  sql:
    init:
      mode: always
  
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    kr.co.webcrawlerandnotifier: INFO

# Application Specific Configuration
app:
  notification:
    sender-email: your-email@gmail.com
  crawling:
    default-timeout: 30000
    max-retries: 3
    user-agent: "WebCrawlerAndNotifier/1.0"

# Slack Configuration
slack:
  webhook:
    url: your-slack-webhook-url
  bot:
    token: ${SLACK_BOT_TOKEN:} 